Models/Dish.cs
#pragma warning disable CS8618


using System.ComponentModel.DataAnnotations;
namespace CRUDeliciousCore.Models;

public class Dish
{
    [Key]
    // DishId =========================
    public int DishId {get; set;}


    // Name ========================= 
    [Required]
    public string Name {get; set;}
    

    // Chef ======================== 
    [Required]
    public string Chef {get; set;}


    // Tastiness ======================== 
    [Required]
    [Range(1,5, ErrorMessage = "You must include a Tastiness score between 1 - 5.")]
    public int Tastiness {get; set;}


    // Calories ======================== 
    [Required]
    [Range(1, int.MaxValue, ErrorMessage = "Calories must be greater than 0!")]
    public int Calories {get; set;}

    // Description ======================== 
    [Required]
    public string Description {get; set;}

    // CreatedAt ======================== 
    public DateTime CreatedAt { get; set; } = DateTime.Now;
    


    // UpdatedAt ======================== 
    public DateTime UpdatedAt { get; set; } = DateTime.Now;



}

Models/ErrorViewModel.cs
namespace CRUDeliciousCore.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/MyContext.cs
// We can disable our warnings safely because we know the framework will assign non-null values 
// when it constructs this class for us.
#pragma warning disable CS8618

using Microsoft.EntityFrameworkCore;


//!Update file name here
namespace CRUDeliciousCore.Models;
// the MyContext class represents a session with our MySQL database, allowing us to query for or save data
// DbContext is a class that comes from EntityFramework, we want to inherit its features


//! (MyContext) represents session with our sql db //DbContext is a primary class that allows us to interact (comes with our entity framwork)
public class MyContext : DbContext 
{   
    // This line will always be here. It is what constructs our context upon initialization  
    public MyContext(DbContextOptions options) : base(options) { }    
    // We need to create a new DbSet<Model> for every model in our project that is making a table
    // The name of our table in our database will be based on the name we provide here
    // This is where we provide a plural version of our model to fit table naming standards    

//! update DB Name // update Table Name
    public DbSet<Dish> Dishes { get; set; } 

}

Controllers/DishController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CRUDeliciousCore.Models;
using System.ComponentModel;

namespace CRUDeliciousCore.Controllers;

public class DishController : Controller
{
    private readonly ILogger<DishController> _logger;
    
    // Add field - adding context into our class // "db" can eb any name
    private MyContext db;


    // update below adding context, etc
    public DishController(ILogger<DishController> logger, MyContext context)
    {
        _logger = logger;
        db = context;
    }


    // Get AllDishes Route * ============================================
    [HttpGet("")]
    public IActionResult Index()
    {
        List<Dish> allDishes = db.Dishes.OrderByDescending(d => d.CreatedAt).ToList();
        return View("AllDishes", allDishes);
    }


    // New Route * ============================================
    [HttpGet("dishes/new")]
    public IActionResult NewDish()
    {
        return View("New");
    }


    // Create Dish method ============================================
    [HttpPost("dishes/create")]
    public IActionResult CreateDish(Dish newDish)
    {
        if(!ModelState.IsValid)
        {
            return View("New");
        }
        //! using db table name "Dishes"
        db.Dishes.Add(newDish);
        db.SaveChanges();
        return RedirectToAction("Index");
    }


    // view one Dish method ============================================
    [HttpGet("dishes/{dishId}")]
    public IActionResult ViewDish(int dishId)
    {
        //Query below:
        Dish dish = db.Dishes.FirstOrDefault(dish => dish.DishId == dishId);
        if(dish == null) 
        {
            return RedirectToAction("Index");
        }
        return View("ViewDish", dish );
    }


    // EDIT one dish method ============================================
    [HttpGet("dishes/{dishId}/edit")]
    public IActionResult Edit(int dishId)
    {
        //Query below:
        Dish? dish = db.Dishes.FirstOrDefault(dish => dish.DishId == dishId);
        if(dish == null) 
        {
            return RedirectToAction("Index");
        }
        return View("Edit", dish );
    }

    //Update a dish Method ============================================
    [HttpPost("dishes/{dishId}/update")]
    // MatchCasing to the dishId route
    public IActionResult Update(Dish editDish, int dishId)

    {
        if(!ModelState.IsValid)
        {
            return Edit(dishId);
            // return View("Edit");
        }
        Dish? dish = db.Dishes.FirstOrDefault(dish => dish.DishId == dishId);
        if(dish == null) 
        {
            return RedirectToAction("Index");
        }
        dish.Name = editDish.Name;
        dish.Chef = editDish.Chef;
        dish.Tastiness = editDish.Tastiness;
        dish.Calories = editDish.Calories;
        dish.Description = editDish.Description;
        db.Dishes.Update(dish);
        db.SaveChanges();
        return RedirectToAction("ViewDish", new {dishId = dishId});

    }


    //Delete one dish Method ============================================
    [HttpPost("dishes/{dishId}/delete")]
    public IActionResult Delete(int dishId)
    {
        Dish? dish = db.Dishes.FirstOrDefault(dish => dish.DishId == dishId);
        db.Dishes.Remove(dish);
        db.SaveChanges();
        // ListSortDescription in the all posts for Index*
        return RedirectToAction("Index");
    }



    // Privacy Route ============================================
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CRUDeliciousCore.Models;

namespace CRUDeliciousCore.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Dish/AllDishes.cshtml
@* create view page *@

@{
    ViewData["Title"] = "CRUDelicious";
}

@model List<Dish>

<div class="text-center">
    <header class="d-flex justify-content-center mt-4">
        <h1 class="">Welcome to @ViewData["Title"]</h1>
    </header>
    <div class="d-flex justify-content-center align-items-center">
        <a class="text-dark nav-link" asp-area="" asp-controller="Dish" asp-action="Index">Home</a>|<a class="text-dark nav-link" asp-area="" asp-controller="Dish" asp-action="NewDish">Add a Dish</a>
    </div>

    <div class="d-flex flex-column justify-content-start text-start mt-3">
        <h3>Check out some recent dishes:</h3>
        <hr class="w-75" />

    @* lower case dish can be any name* *@
    @foreach (Dish dish in Model)
    {
        <div>
            <ul class="list-inline">
                <li class="list-inline-item">
                    <a asp-controller="Dish" asp-action="ViewDish" asp-route-dishId="@dish.DishId" class="text-dark p-1">@dish.Name</a> by @dish.Chef</li>
            </ul>
        </div>
    }
    </div>
</div>

Views/Dish/Edit.cshtml
@* Add a New Dish page *@

@model Dish



<div class="w-100 text-center">

    <header class="d-flex justify-content-center mt-4">
        <h1 class="">Edit @Model.Name</h1>
    </header>
    <div class="d-flex justify-content-center align-items-center mb-2">
        <a class="text-dark nav-link" asp-area="" asp-controller="Dish" asp-action="Index">Home</a>|<a class="text-dark nav-link" asp-area="" asp-controller="Dish" asp-action="NewDish">Add a Dish</a>
    </div>


@* CHECK asp-route-"dishId"="...." *@
    <form asp-action="Update" asp-controller="Dish" asp-route-dishId="@Model.DishId" method="post" class="shadow p-3 rounded d-flex p-2 justify-content-center">
        <div class="w-25 me-2 text-start">
        @* section *@
        <div class="mb-3">
            <label asp-for="Chef">Chef's Name</label>
            <input asp-for="Chef" type="text" class="form-control"/>
            <span asp-validation-for="Chef" class="text-danger font-weight-bold"></span>
        </div>
        @* section *@
        <div class="mb-3">
            <label asp-for="Name">Name of Dish</label>
            <input asp-for="Name" type="text" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger font-weight-bold"></span>
        </div>
        @* section *@
        <div class="mb-3">
            <label asp-for="Calories"></label>
            <input asp-for="Calories" type="number" class="form-control"/>
            <span asp-validation-for="Calories" class="text-danger font-weight-bold"></span>
        </div>
        </div>
        @* section *@
        <div class="mb-3 w-25 me-2 text-cente">
            <label asp-for="Tastiness"></label>
            <select asp-for="Tastiness"  class="form-control" name="Tastiness">
                <option value="">Select a number</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
            </select>
            <span asp-validation-for="Tastiness" class="text-danger font-weight-bold"></span>
        </div>

        @* section *@
        <div class="mb-3 w-25 text-start">
            <label asp-for="Description"></label>
            <textarea asp-for="Description" type="text" class="form-control mb-4 text-start"></textarea>
            <span asp-validation-for="Description" class="text-danger font-weight-bold"></span>
        <button class="btn btn-outline-dark shadow">Edit Dish</button>
        </div>


    </form>


</div>

Views/Dish/New.cshtml
@* Add a New Dish page *@

@model Dish


<div class="w-100 text-center">

    <header class="d-flex justify-content-center mt-4">
        <h1 class="">Add a new Dish!</h1>
    </header>
    <div class="d-flex justify-content-center align-items-center mb-2">
        <a class="text-dark nav-link" asp-area="" asp-controller="Dish" asp-action="Index">Home</a>|<a class="text-dark nav-link" asp-area="" asp-controller="Dish" asp-action="NewDish">Add a Dish</a>
    </div>

    <form asp-action="CreateDish" asp-controller="Dish" method="post" class="shadow p-3 rounded d-flex p-2 justify-content-center">
            @* Column 1 *@
        <div class="w-25 me-2 text-start">
            @* section *@
            <div class="mb-3">
                <label asp-for="Chef">Chef's Name</label>
                <input asp-for="Chef" type="text" class="form-control" placeholder="Chef's name here..."/>
                <span asp-validation-for="Chef" class="text-danger font-weight-bold"></span>
            </div>
            @* section *@
            <div class="mb-3">
                <label asp-for="Name">Name of Dish</label>
                <input asp-for="Name" type="text" class="form-control" placeholder="Name of dish here..."/>
                <span asp-validation-for="Name" class="text-danger font-weight-bold"></span>
            </div>
            @* section *@
            <div class="mb-3">
                <label asp-for="Calories"></label>
                <input asp-for="Calories" type="number" class="form-control" placeholder="Number of calories..."/>
                <span asp-validation-for="Calories" class="text-danger font-weight-bold"></span>
            </div>
        </div>

        @* Column 2 - section *@
        <div class="mb-3 w-25 me-2 text-center">
            <label asp-for="Tastiness"></label>
            <select asp-for="Tastiness"  class="form-control" name="Tastiness">
                <option value="">Select a number</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
            </select>
            <span asp-validation-for="Tastiness" class="text-danger font-weight-bold"></span>
        </div>

        @* column3 - section *@
        <div class="mb-3 w-25 text-start">
            <label asp-for="Description" ></label>
            <textarea asp-for="Description" type="text" class="form-control mb-4 text-start" placeholder="Write a description..."></textarea>
            <span asp-validation-for="Description" class="text-danger font-weight-bold"></span>
        <div class="text-end"><button class="btn btn-outline-dark shadow">Add a Dish</button></div>
        </div>


    </form>


</div>

Views/Dish/ViewDish.cshtml
@* view one dish page *@

@model Dish


<div class="text-center">
        <div>
            <header class="d-flex justify-content-center mt-4">
                <h1 class="display-4"> @Model.Name</h1>
            </header>
        <div class="d-flex justify-content-center align-items-center">
            <a class="text-dark nav-link" asp-area="" asp-controller="Dish" asp-action="Index">Home</a>|<a class="text-dark nav-link" asp-area="" asp-controller="Dish" asp-action="NewDish">Add a Dish</a>
        </div>
        <div class="d-flex flex-column text-start">
            <div>
                <h3>@Model.Name by @Model.Chef</h3>
                <hr class="w-75" />
            </div>
            <div class="">
                <h2 class="mt-2 mb-2">Description: @Model.Description</h2>
                <h4 class="mt-2 mb-2">Calories: @Model.Calories</h4>
                <h4 class="mt-2 mb-2">Tastiness: @Model.Tastiness</h4>
            </div>
        </div>
        
            @* CHECK asp-route-"dishId"="...." *@
            <div class="d-flex flex-row align-items-center p-3 justify-content-around">
                <div>
                    <a asp-controller="Dish" asp-action="Edit" asp-route-dishId="@Model.DishId" class=" shadow bg-primary text-dark btn btn-outline-primary">Edit</a>
                </div>
                @* match the "dishId" with the delete method in the dish controller* *@
                <div>
                    <form asp-controller="Dish" asp-action="Delete" asp-route-dishId="@Model.DishId">
                        <button class="bg-danger text-dark shadow btn btn-outline-danger mt-3">Delete</button>
                    </form>
                </div>
            </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUDeliciousCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUDeliciousCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>

    </header>
                        @* REMINDER - UPDATES MAY BE NEEDED - switch home to "tbd"*@
                        
                            @* <div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="Index">Home</a>| <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="NewDish">Add a Dish</a>
                            </div> *@

                        @*^^^ REMINDER - UPDATES MAY BE NEEDED ^^^*@
@* UPDATING LAYOUT *@

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

@* UPDATING LAYOUT *@
@* 
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CRUDeliciousCore - <a asp-area="" asp-controller="Home" asp-action="New">Add a Dish</a>
        </div>
    </footer> *@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>